import type { AuthenticationDirection } from "../AuthenticationDirection.js";
import type { AuthenticationMode } from "../AuthenticationMode.js";
import type { EncryptionMode } from "../EncryptionMode.js";

/**
 * Authenticated and negotiated material used to create a session cipher
 * (port of C# `EncryptionContext`). Initiator/responder values always retain
 * their protocol roles, regardless of which peer creates the cipher.
 */
export interface EncryptionContext {
  /** Shared secret produced by the authentication provider. */
  key: Uint8Array;
  /** Role of the peer creating the cipher. */
  direction: AuthenticationDirection;
  /** Negotiated encryption mode. */
  mode: EncryptionMode;
  /** Negotiated provider protocol name. */
  protocol: string;
  /** Encryption protocols offered by the initiator, in their original wire order. */
  offeredProtocols: readonly string[];
  /** Authentication mode that produced the shared session key. */
  authenticationMode: AuthenticationMode;
  /** Negotiated authentication protocol that produced the shared key. */
  authenticationProtocol: string;
  /** Authentication realm/domain requested by the initiator. */
  domain: string | null;
  /** Fresh public nonce generated by the session initiator. */
  initiatorNonce: Uint8Array;
  /** Fresh public nonce generated by the session responder. */
  responderNonce: Uint8Array;
  /** Initiator address used by address-bound encryption mode. */
  initiatorAddress?: Uint8Array | null;
  /** Responder address used by address-bound encryption mode. */
  responderAddress?: Uint8Array | null;
}
